services:
  - type: web
    name: slide-summarizer-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libreoffice poppler-utils tesseract-ocr
      cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000 